[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Enable forms (if needed in the future)
[build.processing]
  skip_processing = false

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API Redirects - MUST come before the catch-all redirect
[[redirects]]
  from = "/api/search"
  to = "https://catnatrzpjqcwqnppgkf.supabase.co/functions/v1/search"
  status = 200
  force = true

[[redirects]]
  from = "/api/website/:domain"
  to = "https://catnatrzpjqcwqnppgkf.supabase.co/functions/v1/website-by-domain/:domain"
  status = 200
  force = true

[[redirects]]
  from = "/api/technology/:id"
  to = "https://catnatrzpjqcwqnppgkf.supabase.co/functions/v1/technology/:id"
  status = 200
  force = true

# SPA fallback redirect - MUST come last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200